import { GoogleGenerativeAI } from "@google/generative-ai";
import { SettingsService } from "./SettingsService";

export class LLMService {
  private settingsService: SettingsService;

  constructor(settingsService: SettingsService) {
    this.settingsService = settingsService;
  }

  async generateCompletion(systemPrompt: string, userMessage: string, context: string): Promise<string> {
    const settings = await this.settingsService.getSettings();
    
    if (!settings.geminiApiKey) {
      return "ERROR: No API Key provided. Please check Settings.";
    }

    const fullPrompt = `
      ${systemPrompt}

      ### CONTEXT:
      ${context}

      ### USER MESSAGE:
      ${userMessage}
    `;

    console.log(`[LLMService] Sending Prompt: ${fullPrompt.length} chars. Context: ${context.length} chars.`);

    let attempts = 0;
    const maxAttempts = 3;

    while (attempts < maxAttempts) {
        const genAI = new GoogleGenerativeAI(settings.geminiApiKey);
        try {
            const model = genAI.getGenerativeModel({ model: settings.selectedModel });

            const result = await model.generateContent(fullPrompt);
            const response = await result.response;
            return response.text();
        } catch (error: any) {
            attempts++;
            console.error(`Gemini API Error (Attempt ${attempts}/${maxAttempts}):`, error);
            
            // If it's the last attempt, try Fallback
            if (attempts === maxAttempts) {
                 console.warn("Primary model failed. Attempting fallback to gemini-2.0-flash-exp.");
                 try {
                     const fallbackModel = genAI.getGenerativeModel({ model: 'gemini-2.0-flash-exp' });
                     const result = await fallbackModel.generateContent(fullPrompt);
                     const response = await result.response;
                     return `[System: Primary model failed. Response generated by gemini-2.0-flash-exp]\n\n${response.text()}`;
                 } catch (fallbackError: any) {
                     return `ERROR: Gemini API call failed after ${maxAttempts} attempts and fallback. ${error.message}`;
                 }
            }

            // Exponential backoff: 1s, 2s, 4s...
            await new Promise(resolve => setTimeout(resolve, 1000 * Math.pow(2, attempts - 1)));
        }
    }
    
    return "ERROR: Unknown error in LLMService.";
  }
}
